exclude: ^models/
repos:
  - repo: https://gitee.com/fisn/pre-commit-hooks.git
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://gitee.com/mirrors/isort.git
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]

  - repo: https://gitee.com/mirrors/black.git
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://gitee.com/mirrors_gitlab_pycqa/flake8.git
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://gitee.com/mirrors_pre-commit/mirrors-mypy.git
    rev: v0.971
    hooks:
      - id: mypy
        exclude: test
        args: [--disallow-untyped-calls, --disallow-untyped-defs, --check-untyped-defs]
